In [1]:
import sys
import os

project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)

print("Project root:", project_root)

Project root: c:\Users\Admin\Desktop\ipo-predictor

In [2]:
from scraper.chittorgarh_scraper import scrape_ipo_data, save_raw

df = scrape_ipo_data()
print(f"Shape: {df.shape}")
print(f"Columns: {df.columns.tolist()}")
df.head()

Found 10 table(s) on page
Total rows collected: 395
Shape: (395, 11)
Columns: ['IPO Name', 'Listing Date', 'Allotment Price (INR)', 'Listing Return (%)', 'IPO Price', 'Listing Returns (%)', '1 Week Returns (%)', '4 Week Returns (%)', '6 Week Returns (%)', 'IPO Price (INR)', 'IPO Company']

,IPO Name,Listing Date,Allotment Price (INR),Listing Return (%),IPO Price,Listing Returns (%),1 Week Returns (%),4 Week Returns (%),6 Week Returns (%),IPO Price (INR),IPO Company
0,Kissht,5/8/2026,171,22.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Om Power,4/17/2026,175,10.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Powerica,4/2/2026,395,-1.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Sai Parenteral’s,4/2/2026,392,3.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Aeroplane Basmati,4/2/2026,212,-15.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
save_raw(df, "ipo_raw.csv")

Saved 395 rows to c:\Users\Admin\Desktop\ipo-predictor\data\raw\ipo_raw.csv

In [4]:
print("=== Data Types ===")
print(df.dtypes)

print("\n=== Missing Values ===")
print(df.isnull().sum())

=== Data Types ===
IPO Name                 str
Listing Date             str
Allotment Price (INR)    str
Listing Return (%)       str
IPO Price                str
Listing Returns (%)      str
1 Week Returns (%)       str
4 Week Returns (%)       str
6 Week Returns (%)       str
IPO Price (INR)          str
IPO Company              str
dtype: object

=== Missing Values ===
IPO Name                  97
Listing Date               0
Allotment Price (INR)    202
Listing Return (%)       202
IPO Price                291
Listing Returns (%)      193
1 Week Returns (%)       193
4 Week Returns (%)       193
6 Week Returns (%)       193
IPO Price (INR)          297
IPO Company              298
dtype: int64

In [5]:
# Get a full picture of what we have
print("=== All Columns ===")
print(df.columns.tolist())

print("\n=== Missing Values per Column ===")
print(df.isnull().sum())

print("\n=== Non-null counts per column ===")
print(df.count())

print("\n=== Sample from middle of dataset (older years) ===")
df.iloc[100:105]

=== All Columns ===
['IPO Name', 'Listing Date', 'Allotment Price (INR)', 'Listing Return (%)', 'IPO Price', 'Listing Returns (%)', '1 Week Returns (%)', '4 Week Returns (%)', '6 Week Returns (%)', 'IPO Price (INR)', 'IPO Company']

=== Missing Values per Column ===
IPO Name                  97
Listing Date               0
Allotment Price (INR)    202
Listing Return (%)       202
IPO Price                291
Listing Returns (%)      193
1 Week Returns (%)       193
4 Week Returns (%)       193
6 Week Returns (%)       193
IPO Price (INR)          297
IPO Company              298
dtype: int64

=== Non-null counts per column ===
IPO Name                 298
Listing Date             395
Allotment Price (INR)    193
Listing Return (%)       193
IPO Price                104
Listing Returns (%)      202
1 Week Returns (%)       202
4 Week Returns (%)       202
6 Week Returns (%)       202
IPO Price (INR)           98
IPO Company               97
dtype: int64

=== Sample from middle of dataset (older years) ===

,IPO Name,Listing Date,Allotment Price (INR),Listing Return (%),IPO Price,Listing Returns (%),1 Week Returns (%),4 Week Returns (%),6 Week Returns (%),IPO Price (INR),IPO Company
100,Entero Healthcare,2/16/2024,"1,258",-8.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,Rashi Peripherals,2/14/2024,311,3.38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Capital Small Finance Bank,2/14/2024,468,-7.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,Jana Small Finance Bank,2/14/2024,414,-11.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,Apeejay Surrendra Park Hotels,2/12/2024,155,31.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN